package dkr

type AutoGenerated struct {
	Version  string              `yaml:"version"`
	Services map[string]struct { // map des services avec des noms dynamiques
		Image   string   `yaml:"image"`
		Volumes []string `yaml:"volumes"`
	} `yaml:"services"`
	Volumes map[string]struct { // map des volumes avec des noms dynamiques
		Driver     string `yaml:"driver"`
		DriverOpts struct {
			Type   string `yaml:"type"`
			O      string `yaml:"o"`
			Device string `yaml:"device"`
		} `yaml:"driver_opts"`
	} `yaml:"volumes"`
}
