package dkr

import (
	"fmt"
	"testing"

	"gopkg.in/yaml.v3"
)

func Tes(t *testing.T) {
	date := AutoGenerated{
		Version: "1.0",
		Services: map[string]struct {
			Image   string
			Volumes []string
		}{
			"metering": {
				Image:   "metering-image",
				Volumes: []string{"/path/to/volume1", "/path/to/volume2"},
			},
			"otc-container": {
				Image:   "otc-container-image",
				Volumes: []string{"/path/to/volume3"},
			},
		},
		Volumes: map[string]struct {
			Driver     string
			DriverOpts struct {
				Type   string
				O      string
				Device string
			}
		}{
			"app-configs": {
				Driver: "local",
				DriverOpts: struct {
					Type   string
					O      string
					Device string
				}{
					Type:   "nfs",
					O:      "addr=localhost",
					Device: "/mnt/volume",
				},
			},
			"kube-api-access-tppn9": {
				Driver: "local",
				DriverOpts: struct {
					Type   string
					O      string
					Device string
				}{
					Type:   "nfs",
					O:      "addr=localhost",
					Device: "/mnt/volume2",
				},
			},
		},
	}

	yamlData, err := yaml.Marshal(&date)
	if err != nil {
		fmt.Printf("Error while Marshaling. %v", err)
	}

	fmt.Println(" --- YAML ---")
	fmt.Println(string(yamlData))
}
